### ISSUE TITLE
您好，按照您Demo里的，我如果目标组件化出来的代码也是swift写的，必须使用OC写的分类以及相应的Target_Action文件吗 

### ISSUE THREAD

**Issue by cxq1221** [ModulizationDemo/SwfitDemo#1]
您好，按照您Demo里的，我如果目标组件化出来的代码也是swift写的，必须使用OC写的分类以及相应的Target_Action文件吗
上次提的issue我是想使用CTMediator直接找到swift的类及方法

**Comment by casatwy** [comment]
CTMediator我修改了一下，现在是满足你的要求了。我上传了一个[A_swift](https://github.com/ModulizationDemo/A_swift)，这就是一个swift的组件，同时它的target也是由swift写成的。

**Comment by casatwy** [comment]
至于分类的问题，由于分类是单独的一个pod，你可以用objc的category去写，也可以用swift的extension，这都无所谓的，因为category中不做任何业务逻辑。

**Comment by cxq1221** [comment]
@casatwy 恩，好的谢谢
